###########
# BUILDER #
###########

FROM node:16-slim AS builder

WORKDIR /react-frontend

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build


#########
# FINAL #
#########

FROM nginx:1.19.2-alpine

COPY --from=builder /react-frontend/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]