apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docker-django-react-postgres-nginx
  description: Stack Docker con Django, React, PostgreSQL y Nginx
  annotations:
    github.com/project-slug: silviotufi/docker-django-react-postgres-nginx
spec:
  type: service
  lifecycle: experimental
  owner: user:silviotufi