services:

  backend-prod:
    image: ${BACKEND_IMAGE}:${IMAGE_TAG}

    container_name: backend-app-prod

    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - static_volume:/home/app/web/api/static

    networks:
      - prod

    expose:
      - "8000"

    env_file:
      - ./.env.prod

    depends_on:
      db-prod:
        condition: service_healthy

    restart: unless-stopped


  frontend-prod:
    image: ${FRONTEND_IMAGE}:${IMAGE_TAG}

    container_name: frontend

    volumes:
      - static_volume:/home/app/web/api/static

    networks:
      - prod

    ports:
      - "80:80"

    environment:
      NODE_ENV: production

    depends_on:
      - backend-prod

    restart: unless-stopped


  db-prod:
    image: postgres:13.2-alpine

    container_name: db-prod

    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

    networks:
      - prod

    env_file:
      - ./.env.prod.db

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped


volumes:

  postgres_data_prod:

  static_volume:


networks:

  prod: