###########
# BUILDER #
###########

FROM python:3.12-slim-bookworm AS builder

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update \
    && apt-get install -y \
        python3-dev \
        gcc \
        libffi-dev \
        libpq-dev \
        netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY ./requirements ./requirements

RUN pip wheel \
    --no-cache-dir \
    --no-deps \
    --wheel-dir /usr/src/app/wheels \
    -r requirements/production.txt


#########
# FINAL #
#########

FROM python:3.12-slim-bookworm

RUN useradd -ms /bin/bash app

ENV HOME=/home/app
ENV APP_HOME=/home/app/web

RUN mkdir -p \
    $APP_HOME/api/static

WORKDIR $APP_HOME

RUN apt-get update \
    && apt-get install -y \
        libpq5 \
        netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/app/wheels /wheels

RUN pip install \
    --no-cache-dir \
    /wheels/*

COPY ./entrypoint.prod.sh $APP_HOME/entrypoint.prod.sh

COPY . $APP_HOME

RUN chown -R app:app $APP_HOME

USER app

ENTRYPOINT ["/home/app/web/entrypoint.prod.sh"]