
name: CD

on:
  workflow_run:
    workflows:
      - Docker Registry
    types:
      - completed

jobs:

  deploy:
    name: Deploy to Production

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: [self-hosted, cd]

    steps:

      # ==========================================
      # CHECK DOCKER
      # ==========================================

      - name: Check Docker
        run: |
          docker --version
          docker compose version


      # ==========================================
      # GET VERSION
      # ==========================================

      - name: Set image version
        run: |
          echo "IMAGE_TAG=${{ github.event.workflow_run.head_sha }}" >> "$GITHUB_ENV"

          echo "Deploying version:"
          echo "${{ github.event.workflow_run.head_sha }}"


      # ==========================================
      # CREATE PRODUCTION ENVIRONMENT
      # ==========================================

      - name: Create production secrets
        run: |
          cd ~/dockerlabs/prueba5/dodjrepostnginxmain

          cat > .env.prod <<EOF
          BACKEND_IMAGE=ghcr.io/silviotufi/docker-django-react-postgres-nginx-backend
          FRONTEND_IMAGE=ghcr.io/silviotufi/docker-django-react-postgres-nginx-frontend
          IMAGE_TAG=${{ github.event.workflow_run.head_sha }}

          DEBUG=0
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

          POSTGRES_DB=django_prod
          POSTGRES_USER=django
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST=db-prod
          POSTGRES_PORT=5432
          EOF

          cat > .env.prod.db <<EOF
          POSTGRES_DB=django_prod
          POSTGRES_USER=django
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          EOF


      # ==========================================
      # DEPLOY PRODUCTION
      # ==========================================

      - name: Deploy production
        run: |
          cd ~/dockerlabs/prueba5/dodjrepostnginxmain

          docker compose \
            --env-file .env.prod \
            -f compose.prod.yaml \
            pull

          docker compose \
            --env-file .env.prod \
            -f compose.prod.yaml \
            up -d


      # ==========================================
      # CHECK SERVICES
      # ==========================================

      - name: Check production services
        run: |
          cd ~/dockerlabs/prueba5/dodjrepostnginxmain

          docker compose \
            --env-file .env.prod \
            -f compose.prod.yaml \
            ps


      # ==========================================
      # HEALTH CHECK
      # ==========================================

      - name: Health check
        run: |
          curl -f http://localhost

