name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t backend-ci ./backend

      - name: Run Django checks
        run: docker run --rm backend-ci python manage.py check

      - name: Run backend tests
        run: docker run --rm backend-ci python manage.py test


  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend image
        run: docker build -t frontend-ci ./frontend

      - name: Run frontend tests
        run: docker run --rm frontend-ci npm test -- --watchAll=false

      - name: Build frontend application
        run: docker run --rm frontend-ci npm run build