name: Runner Test

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Check runner
        run: |
          echo "Runner funcionando"
          hostname
          whoami
          docker --version
          docker ps